name: esp_doorbuzzer_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  com_flutter_client:
    #path: ../com_flutter_client
    git:
      url: https://github.com/Marc-R2/com_flutter_client.git

  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^0.13.5
  local_auth: ^2.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
